name: "NexusCorp Security Audit"

on: [push] # Se déclenche à chaque envoi de code

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: write # Important pour que l'IA puisse corriger le code

    steps:
      - name: 1. Recuperer le code
        uses: actions/checkout@v4

      - name: 2. Scanner le projet avec Trivy (Rapport JSON)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'json'
          output: 'trivy-report.json'
          severity: 'CRITICAL,HIGH'
          exit-code: '0' # On ne bloque pas encore ici pour générer le SARIF après

      - name: 3. Scanner le projet avec Trivy (Format SARIF pour GitHub)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # C'est ici qu'on fait échouer le pipeline si besoin

      - name: 4. Téléverser les résultats vers GitHub Security
        if: always() # Obligatoire pour voir les alertes même si le scan échoue
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: 5. Sauvegarder le rapport de faille JSON
        if: failure() # Ne s'exécute que si le scan a échoué (étape 3)
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: trivy-report.json
          
# Ajoute cette étape juste AVANT l'étape 6 pour garantir que Python est prêt
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 6. Lancer l'auto-guérison par l'IA
        if: failure()
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Vérifie bien que c'est un SECRET
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U google-generative-ai
          python ai_remediator.py

      - name: 7. Commit et Push du correctif
        if: failure()
        run: |
          git config --global user.name "beeboylinux"
          git config --global user.email "beeboylinux@gmail.com"
          # On vérifie s'il y a vraiment un changement avant de commit pour éviter l'erreur
          git add requirements.txt
          if git diff --staged --quiet; then
            echo "Aucune modification apportée par l'IA."
          else
            git commit -m "fix: auto-remediation of security vulnerabilities by Gemini"
            git push origin HEAD:main
          fi